### ISSUE TITLE
CacheReloadEvent error

### ISSUE THREAD

**Issue by Nat392** [Florianpal1/FAuction#4]
Hi, I installed your plugin yesterday at version 1.6.8, and I have a recurring error about the cache reload.

```
[07:24:26 ERROR]: [global] TaskChain Exception on fr.florianpal.fauction.schedules.CacheSchedule$$Lambda/0x00007f30a2e78000: CacheReloadEvent may only be triggered synchronously.
[07:24:26 ERROR]: [global] Current Action Index was: 0
[07:24:26 WARN]: java.lang.IllegalStateException: CacheReloadEvent may only be triggered synchronously.
[07:24:26 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[07:24:26 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[07:24:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[07:24:26 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[07:24:26 WARN]:        at fauction-1.6.7.jar//fr.florianpal.fauction.managers.commandmanagers.ExpireCommandManager.updateCache(ExpireCommandManager.java:53)
[07:24:26 WARN]:        at fauction-1.6.7.jar//fr.florianpal.fauction.schedules.CacheSchedule.lambda$run$0(CacheSchedule.java:25)
[07:24:26 WARN]:        at fauction-1.6.7.jar//co.aikar.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[07:24:26 WARN]:        at fauction-1.6.7.jar//co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[07:24:26 WARN]:        at fauction-1.6.7.jar//co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[07:24:26 WARN]:        at fauction-1.6.7.jar//co.aikar.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[07:24:26 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[07:24:26 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[07:24:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[07:24:26 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[07:24:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Florianpal1** [comment]
I made a correction in last version
